filebeat.inputs:
  - type: filestream
    id: my-node-app-id
    enabled: true
    paths:
      - /app/app.log
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          # Ignore non-JSON lines so the harvester doesn't crash on startup logs
          ignore_decoding_error: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOST}"]
  api_key: "${ELASTIC_API_KEY}"
  index: "filebeat-v2"

setup.template.enabled: false

setup.ilm.enabled: false
setup.template.name: "node-logs"
setup.template.pattern: "node-logs-*"